import { useColorMode, useToken } from 'native-base'

export const useThemedColor = () => {
  const { colorMode } = useColorMode()
  const [
    primaryStr,
    backgroundBaseStr,
    backgroundNeutralStr,
    backgroundOther90Str,
    accentPrimaryStr,
    accentPrimary10Str,
    accentSecondaryStr,
    accentSecondary10Str,
    accentSecondary50Str,
    textPrimaryStr,
    textSecondaryStr,
    textTertiaryStr,
    textDisableStr,
    dividerStr,
    divider50Str,
    grayWhiteStr,
    grayG300Str,
    grayG200Str,
    greenStr,
  ] = useToken('colors', [
    `${colorMode}.primary`,
    `${colorMode}.backgroundBase`,
    `${colorMode}.backgroundNeutral`,
    `${colorMode}.backgroundOther90`,
    `${colorMode}.accentPrimary`,
    `${colorMode}.accentPrimary10`,
    `${colorMode}.accentSecondary`,
    `${colorMode}.accentSecondary10`,
    `${colorMode}.accentSecondary50`,
    `${colorMode}.textPrimary`,
    `${colorMode}.textSecondary`,
    `${colorMode}.textTertiary`,
    `${colorMode}.textDisable`,
    `${colorMode}.divider`,
    `${colorMode}.divider50`,
    `${colorMode}.grayWhite`,
    `${colorMode}.grayG300`,
    `${colorMode}.grayG200`,
    `${colorMode}.green`,
  ])
  return {
    primary: `${colorMode}.primary`,
    backgroundBase: `${colorMode}.backgroundBase`,
    backgroundNeutral: `${colorMode}.backgroundNeutral`,
    backgroundOther90: `${colorMode}.backgroundOther90`,
    accentPrimary: `${colorMode}.accentPrimary`,
    accentPrimary10: `${colorMode}.accentPrimary10`,
    accentSecondary: `${colorMode}.accentSecondary`,
    accentSecondary10: `${colorMode}.accentSecondary10`,
    accentSecondary50: `${colorMode}.accentSecondary50`,
    textPrimary: `${colorMode}.textPrimary`,
    textSecondary: `${colorMode}.textSecondary`,
    textTertiary: `${colorMode}.textTertiary`,
    textDisable: `${colorMode}.textDisable`,
    divider: `${colorMode}.divider`,
    divider50: `${colorMode}.divider50`,
    grayWhite: `${colorMode}.grayWhite`,
    grayG300: `${colorMode}.grayG300`,
    grayG200: `${colorMode}.grayG200`,
    green: `${colorMode}.green`,
    primaryStr,
    backgroundBaseStr,
    backgroundNeutralStr,
    backgroundOther90Str,
    accentPrimaryStr,
    accentPrimary10Str,
    accentSecondaryStr,
    accentSecondary10Str,
    accentSecondary50Str,
    textPrimaryStr,
    textSecondaryStr,
    textTertiaryStr,
    textDisableStr,
    dividerStr,
    divider50Str,
    grayWhiteStr,
    grayG300Str,
    grayG200Str,
    greenStr,
  }
}
